# Generated by Django 5.2.4 on 2026-08-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=124, unique=True),
        ),
    ]
