# Generated by Django 5.2.4 on 2026-08-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_skills'),
        ('users', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='projects.project'),
        ),
    ]
